# SPDX-License-Identifier: MIT
"""Independently authored paths and deliberate valid-PDF mutations."""
from fractions import Fraction
from pathlib import Path
import struct
import subprocess
import json
import sys
import tempfile
import unittest

import pikepdf

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'scripts'))
import native_vector_geometry as g


class Source:
    def __init__(self, words):
        self.data = struct.pack('<' + 'H' * len(words), *words)
        self.size = len(self.data)

    def read_at(self, offset, size):
        return self.data[offset:offset + min(size, 3)]


def source_paths(words, mode=2, variant='C8'):
    source = Source([*words, 0x8004, 0])
    return g.source_vectors(source, {'text_offset': 0, 'text_length': source.size},
                            variant, mode, (100, 200), 500)


def pdf_paths(content):
    with pikepdf.new() as doc:
        page = doc.add_blank_page(page_size=(100, 100))
        page.Contents = doc.make_stream(content)
        return g.pdf_vectors(page)


def fixture(root):
    # Independently chosen page/origin and endpoints: expected PDF coordinates
    # below are literal decimal observations, not generated by the evaluator.
    records = Source([0x8006, 0xa381, 120, 230, 280, 260,
                      0x8007, 0xa382, 300, 400, 140, 210, 0x8004, 0]).data
    data = bytearray(100)
    data[:4] = b'\xc8\0\0\0'
    struct.pack_into('<II', data, 8, 1, 2)
    struct.pack_into('<4H', data, 28, 100, 200, 400, 500)
    struct.pack_into('<iihHII', data, 80, 100, len(records), 0, 0, 0, 0)
    source = root / 'control.caj'
    source.write_bytes(data + records)
    content = (b'q 0 w 3.8819247877 43.6716538617 m 19.4096239385 40.7602102709 l S Q\n'
               b'q 0 w 21.3505863324 27.1734735140 m 5.8228871816 45.6126162556 l S Q\n')
    pdf = root / 'control.pdf'
    with pikepdf.new() as doc:
        page = doc.add_blank_page(page_size=(38.8192478771, 48.5240598463))
        page.Contents = doc.make_stream(content)
        doc.save(pdf)
    return source, pdf


class NativeVectorTests(unittest.TestCase):
    def test_original_full_document(self):
        with tempfile.TemporaryDirectory() as name:
            source, pdf = fixture(Path(name))
            result = g.inspect(source, pdf, g.digest(source), g.digest(pdf))
            self.assertEqual(result['status'], 'PASS')
            self.assertEqual(result['pages'][0]['source_vectors'], 2)
            self.assertTrue(result['source_and_pdf_unchanged'])

    def test_mutated_position_width_color_order_omission_and_duplicate_fail(self):
        with tempfile.TemporaryDirectory() as name:
            root = Path(name)
            source, original = fixture(root)
            for change in ('position', 'width', 'color', 'order', 'omission', 'duplicate'):
                with self.subTest(change=change), pikepdf.open(original) as doc:
                    content = doc.pages[0].Contents.read_bytes()
                    if change == 'position':
                        content = content.replace(b'3.8819247877', b'4.8819247877')
                    elif change == 'width':
                        content = content.replace(b'0 w', b'1 w')
                    elif change == 'color':
                        content = b'0.5 G\n' + content
                    elif change == 'order':
                        content = b'\n'.join(reversed(content.splitlines()))
                    elif change == 'omission':
                        content = content.splitlines()[0]
                    else:
                        content += content.splitlines()[0]
                    doc.pages[0].Contents = doc.make_stream(content)
                    mutated = root / (change + '.pdf')
                    doc.save(mutated)
                    result = g.inspect(source, mutated, g.digest(source), g.digest(mutated))
                    self.assertEqual(result['status'], 'FAIL', change)
            command = [sys.executable, g.__file__, str(source), str(mutated),
                       '--source-sha256', g.digest(source), '--pdf-sha256', g.digest(mutated)]
            process = subprocess.run(command, capture_output=True, text=True)
            self.assertEqual(process.returncode, 1, process.stderr)
            self.assertEqual(json.loads(process.stdout)['status'], 'FAIL')

    def test_marker_scope_and_mode_zero_vertical_origin(self):
        words = [0x8006, 0xa385, 0xc078, 230, 0xc118, 260]
        normal, _ = source_paths(words)
        legacy, _ = source_paths(words, 0, 'HN-B')
        self.assertEqual(normal[0]['points'][0], (40 * g.UNIT, 450 * g.UNIT))
        self.assertEqual(normal[0]['points'][1][0], 49352 * g.UNIT)
        self.assertEqual(legacy[0]['points'], [(40 * g.UNIT, 455 * g.UNIT),
                                             (200 * g.UNIT, 425 * g.UNIT)])
        for tag, style in ((0x8006, 0xa380), (0x8007, 0xa381), (0x8006, 0xa384)):
            with self.subTest(tag=tag, style=style), self.assertRaises(ValueError):
                source_paths([tag, style, 120, 230, 280, 260])

    def test_radical_vertices_and_local_black_control(self):
        words = [0x8090, 0x1234, 0xc078, 230, 0xc064, 60,
                 0x81ff, 2, 0, 200, 0x8090, 0xffff, 120, 230, 100, 60]
        paths, order = source_paths(words)
        self.assertEqual(order, ['v', 'v'])
        self.assertEqual(paths[0]['points'], [(x * g.UNIT, y * g.UNIT) for x, y in
                                             [(-25, 435), (-5, 455), (30, 410), (50, 470), (140, 470)]])
        self.assertEqual(paths[0]['width'], 4 * g.UNIT)
        self.assertEqual(paths[0]['gray'], Fraction(68, 255))
        self.assertEqual(paths[1]['gray'], 0)
        for x, width, height in ((0x8078, 0xc064, 60), (0xc078, 100, 60),
                                  (120, 29, 60), (120, 100, 44)):
            with self.assertRaises(ValueError):
                source_paths([0x8090, 1, x, 230, width, height])

    def test_paint_order_retains_glyphs_and_excludes_decoration(self):
        expected, order = source_paths([120, 0xd6d0, 0x8006, 0xa381, 120, 230, 280, 260,
                                       0x8010, 1, 120, 230, 280, 230])
        content = (b'BT <4E2D> Tj ET q 0 w 3.8819247877 43.6716538617 m '
                   b'19.4096239385 40.7602102709 l S Q '
                   b'/Artifact BMC /Span <</ActualText <>>> BDC q 0 0 1 1 re W n BT <0041> Tj <0041> Tj ET Q EMC EMC')
        actual, pdf_order = pdf_paths(content)
        self.assertEqual(order, ['g', 'v'])
        self.assertEqual(g.compare(expected, actual, order, pdf_order)['status'], 'PASS')
        changed = content.replace(b'BT <4E2D> Tj ET ', b'') + b' BT <4E2D> Tj ET'
        moved_paths, moved_order = pdf_paths(changed)
        self.assertEqual(g.compare(expected, moved_paths, order, moved_order)['status'], 'FAIL')

    def test_hash_crop_extent_and_operation_limits(self):
        from unittest.mock import patch
        with tempfile.TemporaryDirectory() as name:
            root = Path(name)
            source, pdf = fixture(root)
            with self.assertRaisesRegex(ValueError, 'hash mismatch'):
                g.inspect(source, pdf, '0' * 64, g.digest(pdf))
            for key in ('/MediaBox', '/CropBox'):
                with pikepdf.open(pdf) as doc:
                    doc.pages[0][key] = [0, 0, 10, 10]
                    changed = root / (key[1:] + '.pdf')
                    doc.save(changed)
                with self.subTest(key=key), self.assertRaises(ValueError):
                    g.inspect(source, changed, g.digest(source), g.digest(changed))
            for key, value in (('/Rotate', 90), ('/CropBox', [0, 0, 10, 10])):
                with pikepdf.open(pdf) as doc:
                    doc.Root.Pages[key] = value
                    changed = root / ('inherited-' + key[1:] + '.pdf')
                    doc.save(changed)
                with self.subTest(key=key), self.assertRaises(ValueError):
                    g.inspect(source, changed, g.digest(source), g.digest(changed))
        with pikepdf.new() as doc:
            page = doc.add_blank_page()
            page.Contents = doc.make_stream(b'0 0 m 10 10 l S')
            page.Group = pikepdf.Dictionary(S=pikepdf.Name('/Transparency'))
            with self.assertRaises(ValueError):
                g.pdf_vectors(page)
        with patch.object(g, 'MAX_OPERATIONS', 2), self.assertRaisesRegex(ValueError, 'operation budget'):
            pdf_paths(b'q 0 w 0 0 m 10 10 l S Q')

    def test_reject_unmeasured_stroke_context_and_unbalanced_states(self):
        line = b'0 0 m 10 10 l S'
        for content in (b'1 0 0 1 3 0 cm 1 0 0 1 0 0 cm ' + line,
                        b'q 0 0 1 1 re W n ' + line + b' Q', b'1 J ' + line,
                        b'1 j ' + line, b'2 M ' + line, b'[2 3] 0 d ' + line,
                        b'q ' + line, b'Q', b'0 0 m 1 1 l',
                        b'/Artifact BMC ' + line + b' EMC', b'0 0 2 2 re f'):
            with self.subTest(content=content), self.assertRaises(ValueError):
                pdf_paths(content)


if __name__ == '__main__':
    unittest.main()
