#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate original bounded HN-B navigation controls outside this checkout.

No source documents, viewer fonts, or other converter implementations are read.
Page 5 records are identical in every case. Only the index width and number of
trailing pages vary. Generated bytes and viewer captures must remain external.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct

CODES = (0xd6d0, 0xcec4, 0xc8cb, 0xc9bd, 0xcbae, 0xccea, 0xb5d8, 0xc8d5,
         0xa0c1, 0xa0c2, 0xa0cd, 0xa0f2, 0xa0e7, 0xa0b1, 0xa0b2, 0xa0b3)


def page_records(page):
    if type(page) is not int or not 1 <= page <= 12:
        raise ValueError('control page outside 1 through 12')
    words = [0x8002, 0x1063, 0x801d, 0, 0x8024, 0x2800, 0x8001, 4500]
    for i in range(page):
        words.extend((4800 + i * 150, 0xd6d0))
    if page not in (2, 3, 4):
        for row in range(40):
            words.extend((0x8001, 4700 + row * 170))
            for col in range(40):
                words.extend((4800 + col * 110, CODES[col % len(CODES)]))
    words.extend((0x8004, page))
    return struct.pack('<' + 'H' * len(words), *words)


def document(pages, stride):
    if (type(pages) is not int or pages not in (5, 6, 12)
            or type(stride) is not int or stride not in (12, 20)):
        raise ValueError('measured controls require 5, 6 or 12 pages and 12- or 20-byte indexes')
    header = bytearray(216)
    struct.pack_into('<III', header, 0, 0x4e48, 200, 136)
    struct.pack_into('<IIII', header, 136, 200 if stride == 20 else 0, 0, pages, 2)
    header[152:164] = '北大二扫1.00'.encode('gbk')  # Existing measured format label.
    struct.pack_into('<HHHH', header, 164, 4652, 4274, 5168, 7760)
    index, body = bytearray(), bytearray()
    for page in range(1, pages + 1):
        data = page_records(page)
        index.extend(struct.pack('<' + 'I' * (stride // 4),
                                 216 + pages * stride + len(body), len(data),
                                 *([0] * (stride // 4 - 2))))
        body.extend(data)
    return bytes(header + index + body)  # Original fixtures only; at most 60 KiB.


def generate(output):
    output = output.resolve()
    checkout = Path(__file__).resolve().parents[2]
    if output == checkout or checkout in output.parents:
        raise ValueError('generated controls must remain outside the checkout')
    output.mkdir(exist_ok=False)
    cases = []
    for pages in (5, 6, 12):
        for stride in (12, 20):
            data = document(pages, stride)
            path = output / f'original-{pages}-pages-{stride}-index.caj'
            with path.open('xb') as stream:
                stream.write(data)
            cases.append({'source_path': str(path), 'source_sha256': hashlib.sha256(data).hexdigest(),
                          'pages': pages, 'index_bytes': stride})
    (output / 'manifest.json').write_text(json.dumps(cases, indent=2) + '\n')
    return cases


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    generate(args.output)
